config/routes.rb
Rails.application.routes.draw do
  get 'find/search'
  get 'home/get_ps'
  devise_for :users
  root to: "home#index"
  #root to: 'complainants#index'

  resources :complaints
  resources :occurances
  resources :victims
  resources :stolen_mobiles
  resources :complainants
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/complaint.rb
class Complaint < ApplicationRecord
  belongs_to :complainant
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  before_action :set_complaint, only: [:show, :edit, :update, :destroy]

  # GET /complaints
  # GET /complaints.json
  def index
    @complaints = Complaint.all
  end

  # GET /complaints/1
  # GET /complaints/1.json
  def show
  end

  # GET /complaints/new
  def new
    @complaint = Complaint.new
  end

  # GET /complaints/1/edit
  def edit
  end

  # POST /complaints
  # POST /complaints.json
  def create
    @complaint = Complaint.new(complaint_params)

    respond_to do |format|
      if @complaint.save
        format.html { redirect_to @complaint, notice: 'Complaint was successfully created.' }
        format.json { render :show, status: :created, location: @complaint }
      else
        format.html { render :new }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /complaints/1
  # PATCH/PUT /complaints/1.json
  def update
    respond_to do |format|
      if @complaint.update(complaint_params)
        format.html { redirect_to @complaint, notice: 'Complaint was successfully updated.' }
        format.json { render :show, status: :ok, location: @complaint }
      else
        format.html { render :edit }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complaints/1
  # DELETE /complaints/1.json
  def destroy
    @complaint.destroy
    respond_to do |format|
      format.html { redirect_to complaints_url, notice: 'Complaint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complaint
      @complaint = Complaint.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def complaint_params
      params.require(:complaint).permit(:comp_recvd_on, :ref_gde_no, :gde_dt, :gde_ps, :fir_no, :fir_dt, :fir_ps, :usec)
    end
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/views/complaints/_form.html.erb
<%= form_with(model: complaint, local: true) do |form| %>
  <% if complaint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(complaint.errors.count, "error") %> prohibited this complaint from being saved:</h2>

      <ul>
        <% complaint.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :comp_recvd_on %>
    <%= form.date_select :comp_recvd_on %>
  </div>

  <div class="field">
    <%= form.label :ref_gde_no %>
    <%= form.text_field :ref_gde_no %>
  </div>

  <div class="field">
    <%= form.label :gde_dt %>
    <%= form.date_select :gde_dt %>
  </div>

  <div class="field">
    <%= form.label :gde_ps %>
    <%= form.text_field :gde_ps %>
  </div>

  <div class="field">
    <%= form.label :fir_no %>
    <%= form.text_field :fir_no %>
  </div>

  <div class="field">
    <%= form.label :fir_dt %>
    <%= form.date_select :fir_dt %>
  </div>

  <div class="field">
    <%= form.label :fir_ps %>
    <%= form.text_field :fir_ps %>
  </div>

  <div class="field">
    <%= form.label :usec %>
    <%= form.text_field :usec %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/complaints/edit.html.erb
<h1>Editing Complaint</h1>

<%= render 'form', complaint: @complaint %>

<%= link_to 'Show', @complaint %> |
<%= link_to 'Back', complaints_path %>

app/views/complaints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Complaints</h1>

<table>
  <thead>
    <tr>
      <th>Comp recvd on</th>
      <th>Ref gde no</th>
      <th>Gde dt</th>
      <th>Gde ps</th>
      <th>Fir no</th>
      <th>Fir dt</th>
      <th>Fir ps</th>
      <th>Usec</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @complaints.each do |complaint| %>
      <tr>
        <td><%= complaint.comp_recvd_on %></td>
        <td><%= complaint.ref_gde_no %></td>
        <td><%= complaint.gde_dt %></td>
        <td><%= complaint.gde_ps %></td>
        <td><%= complaint.fir_no %></td>
        <td><%= complaint.fir_dt %></td>
        <td><%= complaint.fir_ps %></td>
        <td><%= complaint.usec %></td>
        <td><%= link_to 'Show', complaint %></td>
        <td><%= link_to 'Edit', edit_complaint_path(complaint) %></td>
        <td><%= link_to 'Destroy', complaint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Complaint', new_complaint_path %>

app/views/complaints/new.html.erb
<h1>New Complaint</h1>

<%= render 'form', complaint: @complaint %>

<%= link_to 'Back', complaints_path %>

app/views/complaints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comp recvd on:</strong>
  <%= @complaint.comp_recvd_on %>
</p>

<p>
  <strong>Ref gde no:</strong>
  <%= @complaint.ref_gde_no %>
</p>

<p>
  <strong>Gde dt:</strong>
  <%= @complaint.gde_dt %>
</p>

<p>
  <strong>Gde ps:</strong>
  <%= @complaint.gde_ps %>
</p>

<p>
  <strong>Fir no:</strong>
  <%= @complaint.fir_no %>
</p>

<p>
  <strong>Fir dt:</strong>
  <%= @complaint.fir_dt %>
</p>

<p>
  <strong>Fir ps:</strong>
  <%= @complaint.fir_ps %>
</p>

<p>
  <strong>Usec:</strong>
  <%= @complaint.usec %>
</p>

<%= link_to 'Edit', edit_complaint_path(@complaint) %> |
<%= link_to 'Back', complaints_path %>