config/routes.rb
Rails.application.routes.draw do
  get 'find/search'
  get 'home/get_ps'
  devise_for :users
  root to: "home#index"
  #root to: 'complainants#index'

  resources :complaints
  resources :occurances
  resources :victims
  resources :stolen_mobiles
  resources :complainants
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/stolen_mobile.rb
class StolenMobile < ApplicationRecord
  belongs_to :complainant
end

app/controllers/stolen_mobiles_controller.rb
class StolenMobilesController < ApplicationController
  before_action :set_stolen_mobile, only: [:show, :edit, :update, :destroy]

  # GET /stolen_mobiles
  # GET /stolen_mobiles.json
  def index
    @stolen_mobiles = StolenMobile.all
  end

  # GET /stolen_mobiles/1
  # GET /stolen_mobiles/1.json
  def show
  end

  # GET /stolen_mobiles/new
  def new
    @stolen_mobile = StolenMobile.new
  end

  # GET /stolen_mobiles/1/edit
  def edit
  end

  # POST /stolen_mobiles
  # POST /stolen_mobiles.json
  def create
    @stolen_mobile = StolenMobile.new(stolen_mobile_params)

    respond_to do |format|
      if @stolen_mobile.save
        format.html { redirect_to @stolen_mobile, notice: 'Stolen mobile was successfully created.' }
        format.json { render :show, status: :created, location: @stolen_mobile }
      else
        format.html { render :new }
        format.json { render json: @stolen_mobile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stolen_mobiles/1
  # PATCH/PUT /stolen_mobiles/1.json
  def update
    respond_to do |format|
      if @stolen_mobile.update(stolen_mobile_params)
        format.html { redirect_to @stolen_mobile, notice: 'Stolen mobile was successfully updated.' }
        format.json { render :show, status: :ok, location: @stolen_mobile }
      else
        format.html { render :edit }
        format.json { render json: @stolen_mobile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stolen_mobiles/1
  # DELETE /stolen_mobiles/1.json
  def destroy
    @stolen_mobile.destroy
    respond_to do |format|
      format.html { redirect_to stolen_mobiles_url, notice: 'Stolen mobile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stolen_mobile
      @stolen_mobile = StolenMobile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stolen_mobile_params
      params.require(:stolen_mobile).permit(:imei, :stolen_mobno, :service_provider, :make, :model, :color)
    end
end

app/helpers/stolen_mobiles_helper.rb
module StolenMobilesHelper
end

app/views/stolen_mobiles/_form.html.erb
<%= form_with(model: stolen_mobile, local: true) do |form| %>
  <% if stolen_mobile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stolen_mobile.errors.count, "error") %> prohibited this stolen_mobile from being saved:</h2>

      <ul>
        <% stolen_mobile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :imei %>
    <%= form.text_field :imei %>
  </div>

  <div class="field">
    <%= form.label :stolen_mobno %>
    <%= form.text_field :stolen_mobno %>
  </div>

  <div class="field">
    <%= form.label :service_provider %>
    <%= form.text_field :service_provider %>
  </div>

  <div class="field">
    <%= form.label :make %>
    <%= form.text_field :make %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stolen_mobiles/edit.html.erb
<h1>Editing Stolen Mobile</h1>

<%= render 'form', stolen_mobile: @stolen_mobile %>

<%= link_to 'Show', @stolen_mobile %> |
<%= link_to 'Back', stolen_mobiles_path %>

app/views/stolen_mobiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stolen Mobiles</h1>

<table>
  <thead>
    <tr>
      <th>Imei</th>
      <th>Stolen mobno</th>
      <th>Service provider</th>
      <th>Make</th>
      <th>Model</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stolen_mobiles.each do |stolen_mobile| %>
      <tr>
        <td><%= stolen_mobile.imei %></td>
        <td><%= stolen_mobile.stolen_mobno %></td>
        <td><%= stolen_mobile.service_provider %></td>
        <td><%= stolen_mobile.make %></td>
        <td><%= stolen_mobile.model %></td>
        <td><%= stolen_mobile.color %></td>
        <td><%= link_to 'Show', stolen_mobile %></td>
        <td><%= link_to 'Edit', edit_stolen_mobile_path(stolen_mobile) %></td>
        <td><%= link_to 'Destroy', stolen_mobile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stolen Mobile', new_stolen_mobile_path %>

app/views/stolen_mobiles/new.html.erb
<h1>New Stolen Mobile</h1>

<%= render 'form', stolen_mobile: @stolen_mobile %>

<%= link_to 'Back', stolen_mobiles_path %>

app/views/stolen_mobiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Imei:</strong>
  <%= @stolen_mobile.imei %>
</p>

<p>
  <strong>Stolen mobno:</strong>
  <%= @stolen_mobile.stolen_mobno %>
</p>

<p>
  <strong>Service provider:</strong>
  <%= @stolen_mobile.service_provider %>
</p>

<p>
  <strong>Make:</strong>
  <%= @stolen_mobile.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @stolen_mobile.model %>
</p>

<p>
  <strong>Color:</strong>
  <%= @stolen_mobile.color %>
</p>

<%= link_to 'Edit', edit_stolen_mobile_path(@stolen_mobile) %> |
<%= link_to 'Back', stolen_mobiles_path %>