config/routes.rb
Rails.application.routes.draw do
  get 'find/search'
  get 'home/get_ps'
  devise_for :users
  root to: "home#index"
  #root to: 'complainants#index'

  resources :complaints
  resources :occurances
  resources :victims
  resources :stolen_mobiles
  resources :complainants
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/complainant.rb
class Complainant < ApplicationRecord

  has_many :complaints, dependent: :destroy, inverse_of: :complainant
	accepts_nested_attributes_for :complaints, allow_destroy: true, reject_if: :all_blank

  has_many :occurances, dependent: :destroy, inverse_of: :complainant
  accepts_nested_attributes_for :occurances, allow_destroy: true, reject_if: :all_blank

  has_many :stolen_mobiles, dependent: :destroy, inverse_of: :complainant
  accepts_nested_attributes_for :stolen_mobiles, allow_destroy: true, reject_if: :all_blank

  has_many :victims, dependent: :destroy, inverse_of: :complainant
  accepts_nested_attributes_for :victims, allow_destroy: true, reject_if: :all_blank

  # belongs_to :police_district
  # belongs_to :police_station
end

app/controllers/complainants_controller.rb
class ComplainantsController < ApplicationController
  before_action :set_complainant, only: [:show, :edit, :update, :destroy]

  # GET /complainants
  # GET /complainants.json
  def index
    @complainants = Complainant.all.paginate(page: params[:page], per_page: 10)
  end

  # GET /complainants/1
  # GET /complainants/1.json
  def show
  end

  # GET /complainants/new
  def new
    @complainant = Complainant.new
    @complainant.complaints.build
    @complainant.occurances.build
    @complainant.stolen_mobiles.build
    @complainant.victims.build

    # puts "NNNNNNNNNNNNNNEWWWWWWWWWWWWWWWW"
    # @pol_dists = PoliceDistrict.select("ps_dist_code as id", :police_district_name).order("police_district_name")
    # puts "#{@pol_dists.to_json}NNNNNNNNNNNNNEEEEEEEEEEWWWWWW EEEnd"
  end

  # GET /complainants/1/edit
  def edit
  end

  # POST /complainants
  # POST /complainants.json
  def create
    @complainant = Complainant.new(complainant_params)

    respond_to do |format|
      if @complainant.save
        format.html { redirect_to @complainant, notice: 'Complainant was successfully created.' }
        format.json { render :show, status: :created, location: @complainant }
      else
        format.html { render :new }
        format.json { render json: @complainant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /complainants/1
  # PATCH/PUT /complainants/1.json
  def update
    respond_to do |format|
      if @complainant.update(complainant_params)
        format.html { redirect_to @complainant, notice: 'Complainant was successfully updated.' }
        format.json { render :show, status: :ok, location: @complainant }
      else
        format.html { render :edit }
        format.json { render json: @complainant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complainants/1
  # DELETE /complainants/1.json
  def destroy
    @complainant.destroy
    respond_to do |format|
      format.html { redirect_to complainants_url, notice: 'Complainant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complainant
      @complainant = Complainant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def complainant_params
      params.require(:complainant)
        .permit(:name, :address, :ps, :ps_dist, :state, :contact_no,
                complaints_attributes: [:id, :comp_recvd_on, :ref_gde_no, :gde_dt, :gde_ps, :fir_no, :fir_dt, :fir_ps, :usec],
                occurances_attributes: [:id, :date, :time, :place, :ps_dist, :ps, :state, :desc_content],
                stolen_mobiles_attributes: [:id, :imei, :stolen_mobno, :service_provider, :make, :model, :color],
                victims_attributes: [:id, :vic_name, :vic_addr, :ps, :ps_dist, :state, :vic_contct]
                )
    end
end

app/helpers/complainants_helper.rb
module ComplainantsHelper
end

app/views/complainants/_complaint_fields.html.erb
<%# debugger %>
<div class="form-row">
    <div class="form-group col-md-6">
    <%= form.label :comp_recvd_on ,"Complaint received on" %>
    <%= form.text_field :comp_recvd_on ,class: 'form-control',type: 'date'%>
    </div>

    <div class="form-group col-md-6">
    <%= form.label :ref_gde_no %>
    <%= form.text_field :ref_gde_no ,class: 'form-control'%>
    </div>
</div>
<div class="form-row">
  <div class="form-group col-md-6">
    <%= form.label :gde_dt %>
    <%= form.text_field :gde_dt ,class: 'form-control' ,type: 'date'%>
  </div>

  <div class="form-group col-md-6">
    <%= form.label :gde_ps %>
    <%#= form.number_field :gde_ps ,class: 'form-control'%>
      <%#= form.collection_select(:gde_ps,PoliceStation.all.order("ps_name"),:id,:ps_name,{include_blank: 'Select police station'} ,class: 'form-control' )%>
      <%= form.grouped_collection_select(:gde_ps, PoliceDistrict.order("ps_dist_name"), :police_stations, :ps_dist_name, :ps_code, :ps_name, {include_blank: 'Select police station'}, class: 'form-control' )%>
  </div>
</div>
<div class="form-row">
  <div class="form-group col-md-6">
    <%= form.label :fir_no %>
    <%= form.text_field :fir_no ,class: 'form-control'%>
  </div>

  <div class="form-group col-md-6">
    <%= form.label :fir_dt %>
    <%= form.text_field :fir_dt ,class: 'form-control',type: 'date'%>
  </div>
</div>
<div class="form-row">
  <div class="form-group col-md-6">
    <%= form.label :fir_ps %>
    <%#= form.number_field :fir_ps ,class: 'form-control'%>
      <%#= form.collection_select(:fir_ps,PoliceStation.all.order("ps_name"),:id,:ps_name,{include_blank: 'Select police station'} ,class: 'form-control' )%>
      <%= form.grouped_collection_select(:fir_ps, PoliceDistrict.order("ps_dist_name"), :police_stations, :ps_dist_name, :ps_code, :ps_name, {include_blank: 'Select police station'}, class: 'form-control' )%>
  </div>

  <div class="form-group col-md-6">
    <%= form.label :usec %>
    <%= form.text_field :usec ,class: 'form-control'%>
  </div>
</div>

app/views/complainants/_complaint_fields_copy.html.erb
<hr>
  <%# debugger %>
  <div class="field">
    <%= form.label :comp_recvd_on %>
    <%= form.date_select :comp_recvd_on %>
  </div>
    <% p "sdfsdfsdfsdf-----------------------------------#{Time.now}" %>
<hr>

app/views/complainants/_form.html.erb
<div class="card shadow mb-12">

    <div class="card-header py-3">
        <h5 class="m-0 font-weight-bold text-primary">Stolen Mobile Complaint Form</h5>
    </div>
    <div class="card-body" style="padding: 11px 15px 15px 13px;">

        <div class="form-group row" style="font-size:13px;padding: 11px 15px 15px 13px;">
            <%= form_with(model: complainant,class: 'col s12', local: true) do |form| %>
            <div class="form-row">
                <% if complainant.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(complainant.errors.count, "error") %> prohibited this complainant from being saved:</h2>

                    <ul>
                        <% complainant.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
                <% end %>
            </div>
            <h3 class="card-title">Basic Details</h3>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <%= form.label :name %>
                    <%= form.text_field :name ,class: 'form-control' %>
                </div>
                <div class="form-group col-md-6">
                    <%= form.label :contact_no %>
                    <%= form.text_field :contact_no ,class: 'form-control'%>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <%= form.label :ps_dist, "Police District"%>
                    <%#= form.number_field :ps_dist %>
                    <%= form.collection_select(:ps_dist,PoliceDistrict.all.order("ps_dist_name"),:ps_dist_code,:ps_dist_name,{include_blank: 'Select Police District'} ,class: 'form-control' )%>
                </div>
                <div class="form-group col-md-6">
                    <%= form.label :ps ,"Police Station" %>
                    <%#= form.number_field :ps %>
                    <%# debugger %>
                    <!-- <select class="form-control" name="complainant[ps]" id="complainant_ps">
                         </select> -->
                    <%#= form.collection_select(:ps,PoliceStation.all.order("ps_name"),:ps_code,:ps_name,{include_blank: 'Select police station'} ,class: 'form-control' )%>
                    <%= form.grouped_collection_select(:ps, PoliceDistrict.order("ps_dist_name"), :police_stations, :ps_dist_name, :ps_code, :ps_name, {include_blank: 'Select police station'}, class: 'form-control' )%>
                </div>
            </div>


            <div class="form-row">
                <div class="form-group col-md-6">
                    <%= form.label :state %>
                    <%= form.number_field :state, class: "form-control" %>
                </div>
                <div class="form-group col-md-12">
                    <%= form.label :address %>
                    <%= form.text_area :address ,placeholder: 'Enter Your address',class: 'form-control' %>
                </div>
            </div>

            <h3 class="card-title">Complaint </h3>
            <%= form.fields_for :complaints do |comp| %>
            <%= render "complaint_fields", form: comp %>
            <% end %>


            <h3 class="card-title">Occurance</h3>
            <%= form.fields_for :occurances do |oc| %>
            <%= render "occurance_fields", form: oc %>
            <% end %>


            <h3 class="card-title">Stolen Mobile</h3>
            <%= form.fields_for :stolen_mobiles do |st| %>
            <%= render "stolen_mobile_fields", form: st %>
            <% end %>

            <h3 class="card-title">Victim</h3>
            <%= form.fields_for :victims do |vic| %>
            <%= render "victim_fields", form: vic %>
            <% end %>

            <div class="form-row">
                <div class="input-field col-md-4">
                    <%= form.submit  'Submit ' , class: 'btn btn-primary btn-block'%>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

<%# <%= link_to 'Back', complainants_path ,class: 'btn btn-primary' %1> %>

app/views/complainants/_occurance_fields.html.erb
<div class="form-row">
    <div class="form-group col-md-6">
    <%= form.label :date %>
    <%= form.text_field :date ,class: 'form-control' ,type: 'date'%>
    </div>


    <div class="form-group col-md-6">
        <%# debugger %>
        <%= form.label :time %>
        <%= form.time_field :time ,class: 'form-control' ,type: 'time'%>
    </div>
</div>

<div class="form-row">
    <div class="form-group col-md-6">
        <%= form.label :place %>
        <%= form.text_field :place ,class: 'form-control'%>
    </div>
    <div class="form-group col-md-6">
        <%= form.label :ps_district %>
        <%#= form.number_field :ps_district ,class: 'form-control'%>
        <%= form.collection_select(:ps_dist,PoliceDistrict.all.order("ps_dist_name"),:ps_dist_code,:ps_dist_name,{include_blank: 'Select police District'} ,class: 'form-control' )%>
    </div>
</div>


<div class="form-row">
    <div class="form-group col-md-6">
        <%= form.label :ps %>
        <%#= form.number_field :ps ,class: 'form-control'%>
        <%#= form.collection_select(:ps,PoliceStation.all.order("ps_name"),:id,:ps_name,{include_blank: 'Select police station'} ,class: 'form-control' )%>

        <!-- <select class="form-control" name="complainant[occurances_attributes][0][ps]" id="complainant_occurances_attributes_0_ps">
             </select> -->
        <%= form.grouped_collection_select(:ps, PoliceDistrict.order("ps_dist_name"), :police_stations, :ps_dist_name, :ps_code, :ps_name, {include_blank: 'Select police station'}, class: 'form-control' )%>

    </div>

    <div class="form-group col-md-6">
        <%= form.label :state %>
        <%= form.number_field :state ,class: 'form-control'%>
    </div>
</div>
<div class="form-row">
    <div class="form-group col-md-12">
        <%= form.label :description %>
        <%#= form.text_area :description, class: 'form-control'%>
        <%= form.rich_text_area :desc_content ,class: 'form-control'  %>
    </div>
</div>

app/views/complainants/_stolen_mobile_fields.html.erb
<div class="form-row">
    <div class="form-group col-md-6">
    <%= form.label :imei %>
    <%= form.text_field :imei ,class: 'form-control'%>
    </div>

    <div class="form-group col-md-6">
        <%= form.label :stolen_mobno %>
        <%= form.text_field :stolen_mobno ,class: 'form-control'%>
    </div>
</div>

<div class="form-row">
    <div class="form-group col-md-6">
        <%= form.label :service_provider %>
        <%= form.text_field :service_provider ,class: 'form-control'%>
    </div>

    <div class="form-group col-md-6">
        <%= form.label :make %>
        <%= form.text_field :make ,class: 'form-control'%>
    </div>
</div>

<div class="form-row">
    <div class="form-group col-md-6">
        <%= form.label :model %>
        <%= form.text_field :model ,class: 'form-control'%>
    </div>

    <div class="form-group col-md-6">
        <%= form.label :color %>
        <%= form.text_field :color ,class: 'form-control'%>
    </div>
</div>

app/views/complainants/_victim_fields.html.erb
<div class="form-row">
    <div class="form-group col-md-6">
        <%= form.label :vic_name %>
        <%= form.text_field :vic_name ,class: 'form-control'%>
    </div>

    <div class="form-group col-md-6">
        <%= form.label :vic_addr %>
        <%= form.text_field :vic_addr ,class: 'form-control'%>
    </div>
</div>
<div class="form-row">
    <div class="form-group col-md-6">
            <%= form.label :ps_dist %>
            <%#= form.number_field :ps_dist ,class: 'form-control'%>
            <%= form.collection_select(:ps_dist,PoliceDistrict.all.order("ps_dist_name"),:ps_dist_code,:ps_dist_name,{include_blank: 'Select police District'} ,class: 'form-control' )%>
    </div>
    <div class="form-group col-md-6">
        <%= form.label :ps %>
        <%#= form.number_field :ps ,class: 'form-control'%>
        <%#= form.collection_select(:ps,PoliceStation.all.order("ps_name"),:id,:ps_name,{include_blank: 'Select police station'} ,class: 'form-control' )%>

        <select class="form-control" name="complainant[victims_attributes][0][ps]" id="complainant_victims_attributes_0_ps">
        </select>
    </div>

</div>
<div class="form-row">
    <div class="form-group col-md-6">
        <%= form.label :state %>
        <%= form.number_field :state ,class: 'form-control' %>
    </div>

    <div class="form-group col-md-6">
        <%= form.label :vic_contct %>
        <%= form.text_field :vic_contct ,class: 'form-control'%>
    </div>
</div>

app/views/complainants/edit.html.erb
<h1 class="h3 mb-2 text-gray-800">Editing Complainant</h1>
<p class="mb-4">Edit the complainant</p>

<%= render 'form', complainant: @complainant %>

<%= link_to 'Show', @complainant ,class: 'btn btn-primary' %> |
<%= link_to 'Back', complainants_path ,class: 'btn btn-primary' %>

app/views/complainants/index.html.erb
<p id="notice"><%= notice %></p>
<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">All Complaint</h1>
<p class="mb-4">Table representation of all complain</p>


<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Complainants</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hovered">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Address</th>
                        <th scope="col">Police Station</th>
                        <th scope="col">Police dist</th>
                        <th scope="col">State</th>
                        <th scope="col">Contact no</th>
                        <th colspan="3">Action</th>
                    </tr>
                </thead>

                <tbody>
                    <% @complainants.each do |complainant| %>
                    <tr>
                        <td><%= complainant.name %></td>
                        <td><%= complainant.address %></td>
                        <td><%= PoliceStation.select(:ps_name).find_by_ps_code(complainant.ps).ps_name if complainant.ps %></td>
                        <td><%= PoliceDistrict.select(:ps_dist_name).find_by_ps_dist_code(complainant.ps_dist).ps_dist_name if complainant.ps_dist %></td>
                        <td>West Bengal</td>
                        <td><%= complainant.contact_no %></td>
                        <td><%= link_to '<i class="fa fa-eye"></i>'.html_safe, complainant %></td>
                        <td><%= link_to '<i class="fa fa-pen"></i>'.html_safe, edit_complainant_path(complainant) %></td>
                        <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, complainant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        
        
        <nav aria-label="Page navigation example">

        <%= page_entries_info(@complainants) %>
        <ul class="pagination">
            <li class="disabled"> <%= will_paginate(@complainants,:previous_label => "Previous", :next_label => "Next",:class=>"pagination",:outer_window => 1,:inner_window => 0) %>

        </ul>
        </nav>            


    </div>
</div>
<%= link_to 'New Complainant', new_complainant_path ,class: 'btn btn-primary' %>

app/views/complainants/new.html.erb
<h1 class="h3 mb-2 text-gray-800">New Complaint</h1>
<p class="mb-4">Fillup the form </p>
<%= render 'form', complainant: @complainant %>

app/views/complainants/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-6">
    <div class="card shadow mb-4">
      <!-- Card Header - Accordion -->
      <a href="#collapseCardExample1" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample">
        <h6 class="m-0 font-weight-bold text-primary">Complaint user details</h6>
      </a>
      <!-- Card Content - Collapse -->
      <div class="collapse show" id="collapseCardExample1">
        <div class="card-body">
          <p>
          <strong>Name</strong>
          <%= @complainant.name %>
          </p>

          <p>
          <strong>Address</strong>
          <%= @complainant.address %>
          </p>

          <p>
          <strong>Police Station</strong>
          <%#= @complainant.ps %>
          <%= PoliceStation.select(:ps_name).find_by_ps_code(@complainant.ps).ps_name if @complainant.ps %>
          </p>

          <p>
          <strong>Police District</strong>
          <%#= @complainant.ps_dist %>
          <%= PoliceDistrict.select(:ps_dist_name).find_by_ps_dist_code(@complainant.ps_dist).ps_dist_name if @complainant.ps_dist %>
          </p>

          <p>
          <strong>State</strong>
          <%= @complainant.state %>
          </p>

          <p>
          <strong>Contact Number</strong>
          <span class="badge badge-info"><%= @complainant.contact_no %></span>
          </p>
        </div>
      </div>
    </div>

  </div>
  <div class="col-md-6">
    <div class="card shadow mb-4">
      <!-- Card Header - Accordion -->
      <a href="#collapseCardExample2" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample">
        <h6 class="m-0 font-weight-bold text-primary">Complaint Details</h6>
      </a>
      <!-- Card Content - Collapse -->
      <div class="collapse show" id="collapseCardExample2">
        <div class="card-body">
          <% @complainant.complaints.each do |cmp| %>
            <p>
            <strong>Complain received on</strong>
            <%= cmp.comp_recvd_on %>
            </p>

            <p>
            <strong>Ref gde no</strong>
            <%= cmp.ref_gde_no %>
            </p>

            <p>
            <strong>Gde date</strong>
            <%= cmp.gde_dt %>
            </p>

            <p>
            <strong>Gde Police Station</strong>
            <%#= cmp.gde_ps %>
            <%= PoliceStation.select(:ps_name).find_by_ps_code(cmp.gde_ps).ps_name if cmp.gde_ps %>
            </p>

            <p>
            <strong>Fir No</strong>
            <%= cmp.fir_no %>
            </p>

            <p>
            <strong>Fir date</strong>
            <%= cmp.fir_dt %>
            </p>

            <p>
            <strong>Fir Police Station</strong>
            <%= cmp.fir_ps %>
            <%= PoliceStation.select(:ps_name).find_by_ps_code(cmp.fir_ps).ps_name if cmp.fir_ps %>
            </p>

            <p>
            <strong>Under Section</strong>
            <%= cmp.usec %>
            </p>
            <b>
              <hr></b>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <div class="card shadow mb-4">
      <!-- Card Header - Accordion -->
      <a href="#collapseCardExample3" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample">
        <h6 class="m-0 font-weight-bold text-primary">Occurances</h6>
      </a>
      <!-- Card Content - Collapse -->
      <div class="collapse show" id="collapseCardExample3">
        <div class="card-body">

          <% @complainant.occurances.each do |oc| %>
            <p>
            <strong>Date</strong>
            <%= oc.date %>
            </p>

            <p>
            <strong>Time</strong>
            <%= oc.time %>
            </p>

            <p>
            <strong>Place</strong>
            <%= oc.place %>
            </p>

            <p>
            <strong>Police district</strong>
            <%#= oc.ps_dist %>
            <%# debugger %>
            <%= PoliceDistrict.select(:ps_dist_name).find_by_ps_dist_code(oc.ps_dist).ps_dist_name if oc.ps_dist %>

            </p>

            <p>
            <strong>Police Station</strong>
            <%#= oc.ps %>
            <%= PoliceStation.select(:ps_name).find_by_ps_code(oc.ps).ps_name if oc.ps %>
            </p>

            <p>
            <strong>State</strong>
            <%= oc.state %>
            </p>

            <p>
            <strong>Description</strong>
            <%= oc.desc_content %>
            </p>
            <b>
              <hr></b>
          <% end %>
        </div>
      </div>
    </div>

  </div>
  <div class="col-md-6">
    <div class="card shadow mb-4">
      <!-- Card Header - Accordion -->
      <a href="#collapseCardExample4" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample">
        <h6 class="m-0 font-weight-bold text-primary">Stolen Mobile Details</h6>
      </a>
      <!-- Card Content - Collapse -->
      <div class="collapse show" id="collapseCardExample4">
        <div class="card-body">
          <% @complainant.stolen_mobiles.each do |st| %>
            <p>
            <strong>IMEI Number</strong>
            <span class="badge badge-primary"><%= st.imei %></span>
            </p>

            <p>
            <strong>Stolen Mobile No</strong>
            <span class="badge badge-primary"><%= st.stolen_mobno %></span>
            </p>

            <p>
            <strong>Service provider</strong>
            <%= st.service_provider %>
            </p>

            <p>
            <strong>Make By</strong>
            <%= st.make %>
            </p>

            <p>
            <strong>Model Name</strong>
            <%= st.model %>
            </p>

            <p>
            <strong>Color</strong>
            <%= st.color %>
            </p>
          <% end %>
          <b>
            <hr></b>
        </div>
      </div>
    </div>

  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="card shadow mb-4">
      <!-- Card Header - Accordion -->
      <a href="#collapseCardExample5" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample">
        <h6 class="m-0 font-weight-bold text-primary">Victims</h6>
      </a>
      <!-- Card Content - Collapse -->
      <div class="collapse show" id="collapseCardExample5">
        <div class="card-body">

          <% @complainant.victims.each do |vic|  %>
            <p>
            <strong>Vitim name:</strong>
            <%= vic.vic_name %>
            </p>

            <p>
            <strong>Victim address</strong>
            <%= vic.vic_addr %>
            </p>

            <p>
            <strong>Police Station</strong>
            <%#= vic.ps %>
            <%= PoliceStation.select(:ps_name).find_by_ps_code(vic.ps).ps_name if vic.ps %>

            </p>

            <p>
            <strong>Police District</strong>
            <%#= vic.ps_dist %>
            <%= PoliceDistrict.select(:ps_dist_name).find_by_ps_dist_code(vic.ps_dist).ps_dist_name if vic.ps_dist %>
            </p>

            <p>
            <strong>State</strong>
            <%= vic.state %>
            </p>

            <p>
            <strong>Victim contact</strong>
            <span class="badge badge-info"><%= vic.vic_contct %></span>
            </p>

            <b>
              <hr></b>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_complainant_path(@complainant) ,class: 'btn btn-primary' %> &nbsp;
<%= link_to 'Back', complainants_path ,class: 'btn btn-primary' %>