config/routes.rb
Rails.application.routes.draw do
  get 'find/search'
  get 'home/get_ps'
  devise_for :users
  root to: "home#index"
  #root to: 'complainants#index'

  resources :complaints
  resources :occurances
  resources :victims
  resources :stolen_mobiles
  resources :complainants
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/complainant.rb
class Complainant < ApplicationRecord

  has_many :complaints, dependent: :destroy, inverse_of: :complainant
	accepts_nested_attributes_for :complaints, allow_destroy: true, reject_if: :all_blank

  has_many :occurances, dependent: :destroy, inverse_of: :complainant
  accepts_nested_attributes_for :occurances, allow_destroy: true, reject_if: :all_blank

  has_many :stolen_mobiles, dependent: :destroy, inverse_of: :complainant
  accepts_nested_attributes_for :stolen_mobiles, allow_destroy: true, reject_if: :all_blank

  has_many :victims, dependent: :destroy, inverse_of: :complainant
  accepts_nested_attributes_for :victims, allow_destroy: true, reject_if: :all_blank

  # belongs_to :police_district
  # belongs_to :police_station
end

app/models/complaint.rb
class Complaint < ApplicationRecord
  belongs_to :complainant
end

app/models/occurance.rb
class Occurance < ApplicationRecord
  belongs_to :complainant

  has_rich_text :desc_content
end

app/models/police_district.rb
class PoliceDistrict < ApplicationRecord
  has_many :police_stations, foreign_key: 'ps_dist_code', primary_key: 'ps_dist_code'
  validates_uniqueness_of :ps_dist_code
end

app/models/police_station.rb
class PoliceStation < ApplicationRecord
    belongs_to :police_district, foreign_key: 'ps_dist_code', primary_key: 'ps_dist_code'
    validates_uniqueness_of :ps_code
end

app/models/stolen_mobile.rb
class StolenMobile < ApplicationRecord
  belongs_to :complainant
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/victim.rb
class Victim < ApplicationRecord
  belongs_to :complainant
end

app/controllers/find_controller.rb
class FindController < ApplicationController
  def search
    # p "PARAMS::::::::::::::::::::::::::::::::::::: #{params}"

    if params[:query].blank?
      redirect_to(root_path, alert: "Empty field!") and return
    else
      # @results = Complainant.where(contact_no: params[:query])
      @results = Complainant.where("lower(name) like ? or lower(address) like ? or contact_no like ?", "%#{params[:query].downcase}%", "%#{params[:query].downcase}%", "%#{params[:query].downcase}%")
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @complainants = Complainant.all
    @complaints = Complaint.all
    @victims = Victim.all
    @stolen_mobiles = StolenMobile.all
    @occurances = Occurance.all
  end

  def get_ps
    render json: PoliceStation.select(:ps_code, :ps_name).where(ps_dist_code: params[:ps_dist_id])
  end
end

app/controllers/victims_controller.rb
class VictimsController < ApplicationController
  before_action :set_victim, only: [:show, :edit, :update, :destroy]

  # GET /victims
  # GET /victims.json
  def index
    @victims = Victim.all
  end

  # GET /victims/1
  # GET /victims/1.json
  def show
  end

  # GET /victims/new
  def new
    @victim = Victim.new
  end

  # GET /victims/1/edit
  def edit
  end

  # POST /victims
  # POST /victims.json
  def create
    @victim = Victim.new(victim_params)

    respond_to do |format|
      if @victim.save
        format.html { redirect_to @victim, notice: 'Victim was successfully created.' }
        format.json { render :show, status: :created, location: @victim }
      else
        format.html { render :new }
        format.json { render json: @victim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /victims/1
  # PATCH/PUT /victims/1.json
  def update
    respond_to do |format|
      if @victim.update(victim_params)
        format.html { redirect_to @victim, notice: 'Victim was successfully updated.' }
        format.json { render :show, status: :ok, location: @victim }
      else
        format.html { render :edit }
        format.json { render json: @victim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /victims/1
  # DELETE /victims/1.json
  def destroy
    @victim.destroy
    respond_to do |format|
      format.html { redirect_to victims_url, notice: 'Victim was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_victim
      @victim = Victim.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def victim_params
      params.require(:victim).permit(:vic_name, :vic_addr, :ps, :ps_dist, :state, :vic_contct)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def will_paginate(collection_or_options = nil, options = {})
      if collection_or_options.is_a? Hash
      options, collection_or_options = collection_or_options, nil
      end
      unless options[:renderer]
      options = options.merge renderer: WillPaginate::ActionView::BootstrapLinkRenderer
      end
      super *[collection_or_options, options].compact
  end

end

app/helpers/complainants_helper.rb
module ComplainantsHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/find_helper.rb
module FindHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/occurances_helper.rb
module OccurancesHelper
end

app/helpers/stolen_mobiles_helper.rb
module StolenMobilesHelper
end

app/helpers/victims_helper.rb
module VictimsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_header.html.erb
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">


        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-mobile"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Mobile-Theft</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="/">

            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Report Generation
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw  fa-folder "></i>
            <span>All Reports</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Reports</h6>
                <a class="collapse-item" href="javascript:void(0)">Recoverd Mobile </a>
                <a class="collapse-item" href="javascript:void(0)">IMEI Search</a>
                <a class="collapse-item" href="javascript:void(0)">IMEI Pending</a>
                <a class="collapse-item" href="javascript:void(0)">Log Reports</a>


            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Entry Form
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Complaint</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <!-- <h6 class="collapse-header">Complaint</h6> -->
                <%= link_to "All Complainants", complainants_path, :target=> '_parent' ,class: 'collapse-item' %>
                <%= link_to "New Complainant", new_complainant_path, :target=> '_parent' ,class: 'collapse-item' %>
               
            </div>
        </div>
    </li>

    <!-- Nav Item - Charts -->


    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->

<!-- Content Wrapper -->
<div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

            <!-- Sidebar Toggle (Topbar) -->
            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                <i class="fa fa-bars"></i>
            </button>

            <!-- Topbar Search -->
            <!-- <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"> -->
            <%= form_tag(find_search_path, :class => 'd-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search', :method => "get") do %>
                <div class="input-group">
                    <!-- <input type="text" class="form-control bg-light border-0 small" placeholder="Search for... IMEI" aria-label="Search" aria-describedby="basic-addon2"> -->
                    <%= search_field_tag :query, params[:query], placeholder: "Enter Phone number", class: "form-control bg-light border-0 small" %>
                    <div class="input-group-append">
                        <!-- <button class="btn btn-primary" type="button">
                             <i class="fas fa-search fa-sm"></i>
                             </button> -->
                        <button class="btn btn-primary" id="top_search">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
            <% end %>
            <!-- </form> -->

            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">

                <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                <li class="nav-item dropdown no-arrow d-sm-none">
                     <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                     <i class="fas fa-search fa-fw"></i>
                     </a>
                <!-- Dropdown - Messages -->
                <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                     
                     <%= form_tag(find_search_path, :class => 'form-inline mr-auto w-100 navbar-search', :method => "get") do %>
                     <div class="input-group">
                     <%= search_field_tag :query, params[:query], placeholder: "Enter Phone number", class: "form-control bg-light border-0 small" %>
                    
                     <div class="input-group-append">
                     <button class="btn btn-primary"  id="top_search">
                     <i class="fas fa-search fa-sm"></i>
                     </button>
                     </div>
                     </div>
                     <%end%>
                     </div>
                </li> 

                <div class="topbar-divider d-none d-sm-block"></div>

                <!-- Nav Item - User Information -->
                <li class="nav-item dropdown no-arrow">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%=current_user.email%></span>
                        <img class="img-profile rounded-circle" src="https://cdn2.iconfinder.com/data/icons/ios-7-icons/50/user_male2-128.png">
                    </a>
                    <!-- Dropdown - User Information -->
                    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">

                        <%= link_to "<i class='fas fa-user fa-sm fa-fw mr-2 text-gray-400'></i>Profile".html_safe, edit_user_registration_path, class: 'dropdown-item' %>

                        <div class="dropdown-divider"></div>

                        <%= link_to "<i class='fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400'></i>Logout".html_safe, destroy_user_session_path, method: :delete , class: 'dropdown-item' %>

                    </div>
                </li>

            </ul>

        </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>MobileTheft</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" integrity="sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ=" crossorigin="anonymous" />
	<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
	  </head>

	<body id="page-top">
		<div id="wrapper">

		
	
		
		<% if user_signed_in? %>

		<%= render "layouts/header" %>

		<%end%>
		
			
		<div class="container-fluid">  
			<%= yield %>
		</div>
		
		</div>
	
  	</body>
</head>



</html>